### ISSUE TITLE
Do now

### ISSUE THREAD

**Issue by JBYT27** [iop3/Pinnapple#1]
Now all you have to do is create the recipe in all PL. 
And ur done :D

**Comment by JBYT27** [comment]
Like in python, ruby, html, javascript, java, etc.

**Comment by iop3** [comment]
alright!

**Comment by JBYT27** [comment]
:0 poggers xD

**Comment by iop3** [comment]
:D

**Comment by theiocoder** [comment]
I have provided you with an **image**:
![the all-powerful pineapple!](https://user-images.githubusercontent.com/64909897/121519605-e8680600-c9bf-11eb-8bd2-edf08ed9579e.png)
and yes very poggers

**Comment by iop3** [comment]
can you get a image that has a transparent background. Thanks.

**Comment by theiocoder** [comment]
okay:
![transarent pineapple](https://user-images.githubusercontent.com/64909897/122215542-548fb180-ce79-11eb-9aef-049b4c1fdf64.png)

**Comment by theiocoder** [comment]
I also made a few pr's for the c languages, i will add more languages if you want me to

**Comment by iop3** [comment]
thanks!!

**Comment by iop3** [comment]
> ###### (ik the image is a little weird, but its the best i could do)

it's fine! :)

**Comment by firefish111** [comment]
brrrr

**Comment by thequackyduck** [comment]
brrrrrrrrrrrrrrrrr

**Comment by firefish111** [comment]
yes
